name: Deploy Containerized Solution

on:
  push:
    branches: [main]
    paths: ['containerized-solution/**']
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: containerized-solution/terraform

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Build and Deploy Application
        working-directory: containerized-solution/scripts/local
        run: |
          chmod +x build-push-fastapi.sh deploy-to-swarm.sh
          ./build-push-fastapi.sh
          ./deploy-to-swarm.sh
