name: Deploy Serverless Solution

on:
  push:
    branches: [main]
    paths: ['serverless-solution/**']
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Infrastructure
        working-directory: serverless-solution/terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Deploy Frontend
        working-directory: serverless-solution/scripts
        run: |
          chmod +x deploy.sh
          ./deploy.sh
